name: tip-build
channels:
 - conda-forge
dependencies:
 - conda-build==3.21.7
 - cxx-compiler==1.0.0
 - gxx_linux-64==11.2.0
 - make==4.3
 - cmake==3.21.3
 - ninja==1.10.2
 - pkgconfig==1.5.5
 - libpcap==1.10.1
 - arrow-cpp==6.0.1
 - spdlog==1.8.5
 - yaml-cpp==0.6.3
 - gmock==1.10.0
 - gtest==1.10.0
 - libtins==4.2
 - gcovr==5.0
 - python==3.9
 
