codecov:
  require_ci_to_pass: yes
  max_report_age: no
coverage:
  round: down
  range: "50...100"
  status:
    project:
      default:
        # Minimum coverage, percent
        target: 60%
        # Allow to drop x% and still pass checks
        threshold: 10%
        if_ci_failed: error
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no
   
