codecov:
  require_ci_to_pass: yes
  max_report_age: no
coverage:
  precision: 1
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80
        threshold: 0%
        branches:
          - master
          - dev
          - staging
    patch:
      default:
        target: auto
        threshold: 80 
        branches:
          - master
          - dev
          - staging
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: no
   
