name: tip-build
channels:
 - conda-forge
dependencies:
 - conda-build
 - cxx-compiler
# - gxx_linux-64
#  - make

 - cmake
 - ninja
 - pkgconfig
 - libpcap
 - arrow-cpp
 - spdlog
 - yaml-cpp
 - gmock
 - gtest
 - libtins
 - gcovr
 
# Notes: solving unpineed env takes an hour! May be good to keep
# unpinned and pinned envs if there is a significant solve time
# diff.
# Is gxx_linux rerequired?
# Does this non-pinned env build in windows?
# If I solve with unpinned and update pinned, does pinned
# solve and build tip in windows?

# Maybe move env yamls into <root>/conda dir and make
# conda/recipes/tip to declutter the repo? 

# Other: should I do the entire tip package build using, as
# closely as possible, the conda-forge recipe? probably

# See email from Daniel Ching about using conda-forge configure
# yaml. Should I use that in the recipe dir to more closely match 
# conda-forge? probably

# Is there a way to pull the tip recipe and the config yaml from
# conda-forge repos so they are always up-to-date?