name: tip-dev
channels:
 - file:///local_channel
dependencies:
 - cxx-compiler
 - make
 - cmake
 - ninja
 - pkgconfig
 - libpcap
 - arrow-cpp
 - spdlog
 - yaml-cpp
 - gmock
 - gtest
 - libtins
 - gcovr
