name: tip-dev
channels:
 - conda-forge
dependencies:
 - cxx-compiler
 - make
 - cmake
 - ninja
 - pkgconfig
 - libpcap
 - arrow-cpp ==6.0.2
 - spdlog
 - yaml-cpp
 - gmock
 - gtest
 - libtins
 - gcovr
