blacklist:
    - name: "*"
whitelist:
    - name: "_libgcc_mutex"
      version: "0.1"
      build: "conda_forge"
    - name: "_openmp_mutex"
      version: "4.5"
      build: "1_gnu"
    - name: "abseil-cpp"
      version: "20210324.2"
      build: "h9c3ff4c_0"
    - name: "arrow-cpp"
      version: "4.0.1"
      build: "py39hbed7f4b_4_cpu"
    - name: "aws-c-cal"
      version: "0.5.11"
      build: "h95a6274_0"
    - name: "aws-c-common"
      version: "0.6.2"
      build: "h7f98852_0"
    - name: "aws-c-event-stream"
      version: "0.2.7"
      build: "h3541f99_13"
    - name: "aws-c-io"
      version: "0.10.5"
      build: "hfb6a706_0"
    - name: "aws-checksums"
      version: "0.1.11"
      build: "ha31a3da_7"
    - name: "aws-sdk-cpp"
      version: "1.8.186"
      build: "hb4091e7_3"
    - name: "bzip2"
      version: "1.0.8"
      build: "h7f98852_4"
    - name: "c-ares"
      version: "1.17.1"
      build: "h7f98852_1"
    - name: "ca-certificates"
      version: "2021.5.30"
      build: "ha878542_0"
    - name: "certifi"
      version: "2021.5.30"
      build: "py39hf3d152e_0"
    - name: "gflags"
      version: "2.2.2"
      build: "he1b5a44_1004"
    - name: "glog"
      version: "0.5.0"
      build: "h48cff8f_0"
    - name: "grpc-cpp"
      version: "1.38.1"
      build: "h36ce80c_0"
    - name: "krb5"
      version: "1.19.1"
      build: "hcc1bbae_0"
    - name: "ld_impl_linux-64"
      version: "2.36.1"
      build: "hea4e1c9_1"
    - name: "libblas"
      version: "3.9.0"
      build: "9_openblas"
    - name: "libbrotlicommon"
      version: "1.0.9"
      build: "h7f98852_5"
    - name: "libbrotlidec"
      version: "1.0.9"
      build: "h7f98852_5"
    - name: "libbrotlienc"
      version: "1.0.9"
      build: "h7f98852_5"
    - name: "libcblas"
      version: "3.9.0"
      build: "9_openblas"
    - name: "libcurl"
      version: "7.77.0"
      build: "h2574ce0_0"
    - name: "libedit"
      version: "3.1.20191231"
      build: "he28a2e2_2"
    - name: "libev"
      version: "4.33"
      build: "h516909a_1"
    - name: "libevent"
      version: "2.1.10"
      build: "hcdb4288_3"
    - name: "libffi"
      version: "3.3"
      build: "h58526e2_2"
    - name: "libgcc-ng"
      version: "9.3.0"
      build: "h2828fa1_19"
    - name: "libgfortran-ng"
      version: "9.3.0"
      build: "hff62375_19"
    - name: "libgfortran5"
      version: "9.3.0"
      build: "hff62375_19"
    - name: "libgomp"
      version: "9.3.0"
      build: "h2828fa1_19"
    - name: "liblapack"
      version: "3.9.0"
      build: "9_openblas"
    - name: "libnghttp2"
      version: "1.43.0"
      build: "h812cca2_0"
    - name: "libopenblas"
      version: "0.3.15"
      build: "pthreads_h8fe5266_1"
    - name: "libpcap"
      version: "1.10.1"
      build: "h7f98852_0"
    - name: "libprotobuf"
      version: "3.16.0"
      build: "h780b84a_0"
    - name: "libssh2"
      version: "1.9.0"
      build: "ha56f1ee_6"
    - name: "libstdcxx-ng"
      version: "9.3.0"
      build: "h6de172a_19"
    - name: "libthrift"
      version: "0.14.2"
      build: "he6d91bd_1"
    - name: "libtins"
      version: "4.3"
      build: "h2703dd9_0"
    - name: "libutf8proc"
      version: "2.6.1"
      build: "h7f98852_0"
    - name: "lz4-c"
      version: "1.9.3"
      build: "h9c3ff4c_0"
    - name: "ncurses"
      version: "6.2"
      build: "h58526e2_4"
    - name: "numpy"
      version: "1.21.0"
      build: "py39hdbf815f_0"
    - name: "openssl"
      version: "1.1.1k"
      build: "h7f98852_0"
    - name: "orc"
      version: "1.6.9"
      build: "h58a87f1_0"
    - name: "pip"
      version: "21.1.3"
      build: "pyhd8ed1ab_0"
    - name: "python"
      version: "3.9.6"
      build: "h49503c6_1_cpython"
    - name: "python_abi"
      version: "3.9"
      build: "2_cp39"
    - name: "re2"
      version: "2021.06.01"
      build: "h9c3ff4c_0"
    - name: "readline"
      version: "8.1"
      build: "h46c0cb4_0"
    - name: "s2n"
      version: "1.0.10"
      build: "h9b69904_0"
    - name: "setuptools"
      version: "49.6.0"
      build: "py39hf3d152e_3"
    - name: "snappy"
      version: "1.1.8"
      build: "he1b5a44_3"
    - name: "spdlog"
      version: "1.8.5"
      build: "h4bd325d_0"
    - name: "sqlite"
      version: "3.36.0"
      build: "h9cd32fc_0"
    - name: "tk"
      version: "8.6.10"
      build: "h21135ba_1"
    - name: "tzdata"
      version: "2021a"
      build: "he74cb21_1"
    - name: "wheel"
      version: "0.36.2"
      build: "pyhd3deb0d_0"
    - name: "xz"
      version: "5.2.5"
      build: "h516909a_1"
    - name: "yaml-cpp"
      version: "0.6.3"
      build: "he1b5a44_4"
    - name: "zlib"
      version: "1.2.11"
      build: "h516909a_1010"
    - name: "zstd"
      version: "1.5.0"
      build: "ha95c52a_0"
