blacklist:
    - name: "*"
whitelist:
    - name: "_libgcc_mutex"
      version: "0.1"
      build: "main"
    - name: "_openmp_mutex"
      version: "4.5"
      build: "1_gnu"
    - name: "arrow-cpp"
      version: "4.0.1"
      build: "py39hced866c_3"
    - name: "aws-c-common"
      version: "0.4.57"
      build: "he6710b0_1"
    - name: "aws-c-event-stream"
      version: "0.1.6"
      build: "h2531618_5"
    - name: "aws-checksums"
      version: "0.1.9"
      build: "he6710b0_0"
    - name: "aws-sdk-cpp"
      version: "1.8.185"
      build: "hce553d0_0"
    - name: "blas"
      version: "1.0"
      build: "mkl"
    - name: "boost-cpp"
      version: "1.73.0"
      build: "h27cfd23_11"
    - name: "brotli"
      version: "1.0.9"
      build: "he6710b0_2"
    - name: "bzip2"
      version: "1.0.8"
      build: "h7b6447c_0"
    - name: "c-ares"
      version: "1.17.1"
      build: "h27cfd23_0"
    - name: "ca-certificates"
      version: "2021.5.25"
      build: "h06a4308_1"
    - name: "certifi"
      version: "2021.5.30"
      build: "py39h06a4308_0"
    - name: "double-conversion"
      version: "3.1.5"
      build: "he6710b0_1"
    - name: "gflags"
      version: "2.2.2"
      build: "he6710b0_0"
    - name: "glog"
      version: "0.5.0"
      build: "h2531618_0"
    - name: "grpc-cpp"
      version: "1.26.0"
      build: "hf8bcb03_0"
    - name: "icu"
      version: "58.2"
      build: "he6710b0_3"
    - name: "intel-openmp"
      version: "2021.2.0"
      build: "h06a4308_610"
    - name: "krb5"
      version: "1.18.2"
      build: "h173b8e3_0"
    - name: "ld_impl_linux-64"
      version: "2.35.1"
      build: "h7274673_9"
    - name: "libboost"
      version: "1.73.0"
      build: "h3ff78a5_11"
    - name: "libcurl"
      version: "7.71.1"
      build: "h20c2e04_1"
    - name: "libedit"
      version: "3.1.20210216"
      build: "h27cfd23_1"
    - name: "libevent"
      version: "2.1.8"
      build: "h1ba5d50_1"
    - name: "libffi"
      version: "3.3"
      build: "he6710b0_2"
    - name: "libgcc-ng"
      version: "9.3.0"
      build: "h5101ec6_17"
    - name: "libgomp"
      version: "9.3.0"
      build: "h5101ec6_17"
    - name: "libpcap"
      version: "1.9.1"
      build: "h7b6447c_0"
    - name: "libprotobuf"
      version: "3.11.2"
      build: "hd408876_0"
    - name: "libssh2"
      version: "1.9.0"
      build: "h1ba5d50_1"
    - name: "libstdcxx-ng"
      version: "9.3.0"
      build: "hd4cf53a_17"
    - name: "libthrift"
      version: "0.13.0"
      build: "hfb8234f_6"
    - name: "libtins"
      version: "4.2"
      build: "h6bb024c_0"
    - name: "lz4-c"
      version: "1.9.3"
      build: "h2531618_0"
    - name: "mkl"
      version: "2021.2.0"
      build: "h06a4308_296"
    - name: "mkl-service"
      version: "2.3.0"
      build: "py39h27cfd23_1"
    - name: "mkl_fft"
      version: "1.3.0"
      build: "py39h42c9631_2"
    - name: "mkl_random"
      version: "1.2.1"
      build: "py39ha9443f7_2"
    - name: "ncurses"
      version: "6.2"
      build: "he6710b0_1"
    - name: "numpy"
      version: "1.20.2"
      build: "py39h2d18471_0"
    - name: "numpy-base"
      version: "1.20.2"
      build: "py39hfae3a4d_0"
    - name: "openssl"
      version: "1.1.1k"
      build: "h27cfd23_0"
    - name: "orc"
      version: "1.6.7"
      build: "h973521d_2"
    - name: "pip"
      version: "21.1.2"
      build: "py39h06a4308_0"
    - name: "python"
      version: "3.9.5"
      build: "h12debd9_4"
    - name: "re2"
      version: "2020.11.01"
      build: "h2531618_1"
    - name: "readline"
      version: "8.1"
      build: "h27cfd23_0"
    - name: "setuptools"
      version: "52.0.0"
      build: "py39h06a4308_0"
    - name: "six"
      version: "1.15.0"
      build: "py39h06a4308_0"
    - name: "snappy"
      version: "1.1.8"
      build: "he6710b0_0"
    - name: "spdlog"
      version: "1.8.5"
      build: "h6bb024c_0"
    - name: "sqlite"
      version: "3.35.4"
      build: "hdfb4753_0"
    - name: "tip"
      version: "1.0.2"
      build: "h6bb024c_4"
    - name: "tk"
      version: "8.6.10"
      build: "hbc83047_0"
    - name: "tzdata"
      version: "2020f"
      build: "h52ac0ba_0"
    - name: "uriparser"
      version: "0.9.3"
      build: "he6710b0_1"
    - name: "utf8proc"
      version: "2.6.1"
      build: "h27cfd23_0"
    - name: "wheel"
      version: "0.36.2"
      build: "pyhd3eb1b0_0"
    - name: "xz"
      version: "5.2.5"
      build: "h7b6447c_0"
    - name: "yaml-cpp"
      version: "0.6.3"
      build: "hf484d3e_4"
    - name: "zlib"
      version: "1.2.11"
      build: "h7b6447c_3"
    - name: "zstd"
      version: "1.4.9"
      build: "haebb681_0"
