{% set name = "tip" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../

build:
  number: 2
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage('tip', max_pin='x.x') }}
  script_env:
    - CI_COMMIT_TAG
    - CI_COMMIT_SHORT_SHA

requirements:
  build:
    - gxx_linux-64 ==11.2.0
    - make ==4.3
    - cmake ==3.21.3
    - ninja ==1.10.2
    - pkgconfig ==1.5.5

  host:
    - libpcap ==1.10.1
    - arrow-cpp ==6.0.1
    - spdlog ==1.8.5
    - yaml-cpp ==0.6.3
    - gmock ==1.10.0
    - gtest ==1.10.0
    - libtins ==4.2

  run:
    - libpcap ==1.10.1
    - arrow-cpp ==6.0.1
    - spdlog ==1.8.5
    - yaml-cpp ==0.6.3
    - gmock ==1.10.0
    - gtest ==1.10.0
    - libtins ==4.2

test:
  commands:
    - tests

about:
  home: https://github.com/IM-USAF/tip
  license: DOD
  license_family: GPL3
  license_file: README.md
  summary: c++ library to process Chapter 10 data

    # test:
    #   commands: test -f $PREFIX/cpp/tests/CMakeLists.txt
