# Used in the conda build CI: .github/workflows/conda-build.yml
name: tip-conda-build
channels:
 - conda-forge
dependencies:
 - conda-build
 - conda-verify
 - python
 - pip
 - pip:
   - ruamel.yaml
   - ruamel.yaml.jinja2
 
