# Used in the conda build CI: .github/workflows/conda-build.yml
name: tip-conda-build
channels:
 - conda-forge
dependencies:
 - conda-build ==24.9.0
 - conda-verify ==3.4.2
 - python ==3.11.10
 - pip ==24.3.1
 - pip:
   - ruamel.yaml
   - ruamel.yaml.jinja2
 
