# Used in the conda build CI: .github/workflows/conda-build.yml
name: tip-conda-build
channels:
 - conda-forge
dependencies:
 - conda-build ==24.3.0
 - conda-verify ==3.1.1
 - python ==3.11.9
 - pip ==24.0
 - pip:
   - ruamel.yaml
   - ruamel.yaml.jinja2
 
