name: conda-build
on:
  push:
    branches-ignore:
      - master
jobs:
  prepare-conda-env:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
            #activate-environment: tip-dev 
            #environment-file: environment.yaml
          auto-activate-base: false
          python-version: 3.9
      - name: Conda info debug 
        shell: bash -l {0} 
        run: conda info
      - name: Conda build
        shell: bash -l {0}
        env: 
          CI_COMMIT_TAG: ${{github.ref_name}}
        run: |
          pushd tip_scripts
          bash ./conda_build.sh    
          popd
