name: main-build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  call-ubuntu-build-job:
    uses: ./.github/workflows/ubuntu-build.yml
    secrets: inherit 
  build-conda-job:
    runs-on: ubuntu-22.04
    env: 
      BUILD_DIR: build
      CODE_COV_FNAME: overall-coverage.xml
      ENV_NAME: tip-build
    steps: 
      - name: Create build dir
        run: mkdir ~/$BUILD_DIR 

      - uses: actions/checkout@v2

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ${{ env.ENV_NAME }}
          environment-file: ci_environment_pinned.yaml
          auto-activate-base: false
          python-version: 3.9

      - name: Conda info debug
        shell: bash -l {0}
        run: conda info

      - name: Conda build
        shell: bash -l {0}
        env: 
          CI_COMMIT_TAG: ${{ github.ref_name }}
          CI_COMMIT_SHORT_SHA: ${{ github.sha }}
          CONDA_RECIPES_DIR: conda-recipes
          
        run: |
          cd $CONDA_RECIPES_DIR
          conda build tip -c conda-forge --croot ~/$BUILD_DIR
          cd ~/$BUILD_DIR
          pwd
          tree
