name: conda-build
on:
  push:
    branches-ignore:
      - master
jobs:
  build-job:
    runs-on: ubuntu-20.04
    env: 
      BUILD_DIR: build-profile
    steps: 
      - uses: actions/checkout@v2
      - name: pwd debug
        run: pwd && ls
      - name: Create build dir
        run: mkdir '${GITHUB_WORKSPACE}/${{ env.BUILD_DIR }}'
      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: tip-build 
          environment-file: ci_environment.yaml
          auto-activate-base: false
          python-version: 3.9
          #- name: Conda info debug
          #shell: bash -l {0}
          #run: conda info
      - name: Conda build
        shell: bash -l {0}
        env: 
          CI_COMMIT_TAG: ${{github.ref_name}}
          CI_COMMIT_SHORT_SHA: ${{github.sha}}
          CONDA_RECIPES_DIR: tip_scripts/conda-recipes
        run: |
          cd $CONDA_RECIPES_DIR
          conda build tip -c conda-forge --croot $BUILD_DIR
          cd '${GITHUB_WORKSPACE}/${{ env.BUILD_DIR }}'
          tree
      - name: Run tests
        shell: bash -l {0}
        run: tests
