name: conda-build
on:
  push:
    branches-ignore:
      - master
jobs:
  build-job:
    runs-on: ubuntu-20.04
    container:
      image: registry.il2.dso.mil/skicamp/project-opal/tip/dev:tip-ghbuild-0.2
      credentials:
        username: ${{ secrets.TIP_REGISTRY_USER }}
        password: ${{ secrets.TIP_REGISTRY_PASS }}
      env:
        DEPS_DIR: /home/tip/deps 
        BUILD_DIR: build-profile
    steps: 
      - name: pwd debug
        run: pwd && ls
      - uses: actions/checkout@v2
      - name: Create build dir
        run: mkdir $BUILD_DIR && ls
      - name: Link to deps
        run: ln -fs $DEPS_DIR ./deps
      - name: Configure CMake
        run: |
          cd $BUILD_DIR
          cmake .. -GNinja
      - name: Build tip binaries
        run: ninja install
      - name: Run tests
        run: ../bin/tests
