name: conda-build
on:
  push:
    branches-ignore:
      - master
jobs:
  build-job:
    runs-on: ubuntu-20.04
    container:
      image: registry.il2.dso.mil/skicamp/project-opal/tip/dev:tip-ghbuild-0.2
      credentials:
        username: ${{ secrets.TIP_REGISTRY_USER }}
        password: ${{ secrets.TIP_REGISTRY_PASS }}
      env:
        DEPS_DIR: /home/tip/deps 
        BUILD_DIR: build-profile
        CI_COMMIT_TAG: ${{github.ref_name}}
        CI_COMMIT_SHORT_SHA: ${{github.sha}}
    steps: 
      - name: pwd debug
        run: pwd && ls
      - uses: actions/checkout@v2
      - name: Create build dir
        run: mkdir $BUILD_DIR && ls
      - name: Link to deps
        run: ln -fs $DEPS_DIR ./deps
      - name: Configure CMake
        run: |
          cd $BUILD_DIR
          cmake .. -GNinja -DCI_COMMIT_TAG=$CI_COMMIT_TAG -DCI_COMMIT_SHORT_SHA=$CI_COMMIT_SHORT_SHA
          #- name: ls in build dir
          #run: pwd && ls
      - name: Build tip binaries
        run: |
            cd $BUILD_DIR
            ninja install
      - name: Run tests
        run: ./bin/tests
