name: ubuntu-ci-image-build
on:
  workflow_call:
jobs:
  check-changed-dockerfile-job:
    runs-on: ubuntu-latest
    env: 
      # DOCKERFILE_PATH: ubuntu_dev.Dockerfile
      DOCKERFILE_PATH: .github/workflows/ubuntu-ci-image-update.yml
    outputs:
      dockerfile-changed-result: ${{ steps.match-changed-files.outputs.changed }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with: 
          # files: ${{ env.DOCKERFILE_PATH }}
          # files: |
            # *.Dockerfile
          match_directories: "false"

      - name: match changed files
        id: match-changed-files
        run: |
            CHANGED="false"
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
              if [[ $file == ${{ env.DOCKERFILE_PATH }} ]]
              then
                echo "Caught ${{ env.DOCKERFILE_PATH }} changing!"
                CHANGED="true"
              fi
            done
            echo "changed=${CHANGED}" >> $GITHUB_OUTPUT

  build-image-job:
    runs-on: ubuntu-latest
    needs: check-changed-dockerfile-job
    if: needs.check-changed-dockerfile-job.outputs.dockerfile-changed-result == 'true'
    steps:
      - name: test job output
        run: echo "=======> build-image-job is running !!!!"

