name: conda-build
on:
  push:
    branches-ignore:
      - master
jobs:
  build-job:
    runs-on: ubuntu-20.04
    container:
      image: registry.il2.dso.mil/skicamp/project-opal/tip/dev:tip-ghbuild-0.2
      credentials:
        username: ${{ secrets.TIP_REGISTRY_USER }}
        password: ${{ secrets.TIP_REGISTRY_PASS }}
      env:
        DEPS_DIR: /home/tip/deps 
        BUILD_DIR: build-profile
    steps: 
      - name: pwd debug
        run: pwd && ls
        #- name: Create build dir
        #run: mkdir $HOME/${{env.BUILD_DIR}} && ls $HOME
      - uses: actions/checkout@v2
      - name: ls debug
        run: pwd && ls
        #- name: Run tests
        #shell: bash -l {0}
        #run: conda info && $PREFIX/bin/tests
