name: ubuntu-ci-image-build
on:
  workflow_call:
env: 
  DOCKERFILE_PATH: ubuntu_dev.Dockerfile
  CI_IMAGE_NAME: ubuntu_ci
  CI_IMAGE_TAG: latest
jobs:
  check-changed-dockerfile-job:
    runs-on: ubuntu-latest
    outputs:
      dockerfile-changed-result: ${{ steps.match-changed-files.outputs.changed }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with: 
          match_directories: "false"

      - name: match changed files
        id: match-changed-files
        run: |
            CHANGED="false"
            for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
              echo "$file was changed"
              if [[ $file == ${{ env.DOCKERFILE_PATH }} ]]
              then
                echo "Caught ${{ env.DOCKERFILE_PATH }} changing!"
                CHANGED="true"
              fi
            done
            echo "changed=${CHANGED}" >> $GITHUB_OUTPUT

  build-image-job:
    runs-on: ubuntu-latest
    needs: check-changed-dockerfile-job
    if: needs.check-changed-dockerfile-job.outputs.dockerfile-changed-result == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Login to ghcr.Io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build CI image
        run: |
          docker build -t ghcr.io/309theddge/tip/${{ env.CI_IMAGE_NAME }}:${{ env.CI_IMAGE_TAG }} - < ${{ env.DOCKERFILE_PATH }}
          docker push ghcr.io/309theddge/tip/${{ env.CI_IMAGE_NAME }}:${{ env.CI_IMAGE_TAG }}


